// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimplzQuestionnaire.Model;

namespace SimplzQuestionnaire.Migrations
{
    [DbContext(typeof(SQContext))]
    partial class SQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SimplzQuestionnaire.Model.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionnaireUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex("QuestionnaireUserId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.QuestionnaireUser", b =>
                {
                    b.Property<int>("QuestionnaireUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionnaireUserId");

                    b.ToTable("QuestionnaireUsers");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.UserAnswer", b =>
                {
                    b.Property<int>("QuestionnaireUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeTaken")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionnaireUserId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionnaireUserId", "AnswerId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Answer", b =>
                {
                    b.HasOne("SimplzQuestionnaire.Model.Question", "Question")
                        .WithMany("Answer")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Question", b =>
                {
                    b.HasOne("SimplzQuestionnaire.Model.Questionnaire", "Questionnaire")
                        .WithMany("Question")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Questionnaire", b =>
                {
                    b.HasOne("SimplzQuestionnaire.Model.QuestionnaireUser", "QuestionnaireUser")
                        .WithMany("Questionnaire")
                        .HasForeignKey("QuestionnaireUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionnaireUser");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.UserAnswer", b =>
                {
                    b.HasOne("SimplzQuestionnaire.Model.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimplzQuestionnaire.Model.QuestionnaireUser", "QuestionnaireUser")
                        .WithMany()
                        .HasForeignKey("QuestionnaireUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("QuestionnaireUser");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.Questionnaire", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("SimplzQuestionnaire.Model.QuestionnaireUser", b =>
                {
                    b.Navigation("Questionnaire");
                });
#pragma warning restore 612, 618
        }
    }
}
